export const ProjectTags = {
  PROFESSIONAL: { label: "Professional", colorScheme: "blue" },
  PERSONAL: { label: "Personal Project", colorScheme: "blue" },
  IN_DEVELOPMENT: { label: "In Development", colorScheme: "purple" },
  LEARNING: { label: "Learning Project", colorScheme: "green" },
  CLIENT: { label: "Client Project", colorScheme: "orange" },
  TEMPLATE: { label: "Template", colorScheme: "yellow" },
  DATA_VIZ: { label: "Data Visualization", colorScheme: "purple" },
  NEXTJS: { label: "Next.js", colorScheme: "gray" },
  REACT: { label: "React", colorScheme: "cyan" },
  THREEJS: { label: "Three.js", colorScheme: "purple" },
  PHP: { label: "PHP", colorScheme: "purple" },
  WORDPRESS: { label: "WordPress", colorScheme: "pink" },
  STATIC: { label: "Static Site", colorScheme: "teal" },
  NLP: { label: "NLP", colorScheme: "green" },
  ASTRO: { label: "Astro", colorScheme: "orange" },
  CLOUDFLARE_WORKERS: { label: "Cloudflare Workers", colorScheme: "orange" },
} as const;
